import os

rename_list = [
    "001a_eraser60_",
    "001b_Happy_birthday_Jess2_",
    "001c_spiral2_",
    "02_Fractal2",
    "03_pnuttrellis_",
    "04_fractaltree_",
    "04_spiralsquares2_(E)_",
    "05_Spiral_Gyrations_",
    "06_secretgarden_",
    "07_ChartresLabyrinthe_",
    "08_11loop2",
    "09b_Ackling_star_",
    "10_wave1_",
    "12_dithersunburst_",
    "13b_Battlesbury_",
    "14b_Binarysupport_",
    "15_Bunch_of_Valentines_",
    "16b_buckland_",
    "17_BurstyBezier_",
    "18b_butterfly_",
    "19_Itsyourmove_",
    "20b_cells_",
    "21b_cheesefoot_",
    "22b_cleyhill_",
    "23b_complexwoman_",
    "24_coolballs_",
    "25b_Enjoy_Your_Day",
    "25_eraser40_",
    "26b_fractal_quilt",
    "27b_gears_",
    "28_fractal_spirograph_1_",
    "29_Hackpenhill_",
    "30_Heart_Sunshine_",
    "31_Hosta_",
    "32_loop4_",
    "33b_Milkhill_",
    "33_Labyrinth1_",
    "34_raisedstar_5_",
    "35b_Lucy_Bird_",
    "36_Wave2_",
    "37_SpiralBezier_",
    "38b_WinterbourneBassett_",
    "39_Loop1",
    "40_summer_",
    "41b_hillscross_",
    "42_Hexigon_Alley_Tightcode_",
    "43_hyptnogrid_",
    "44_linedcircles_",
    "45_Petalar_",
    "46b_WiltonWindmill_",
    "47_Maze2_(S_S)_",
    "48_Wormhole_",
    "49b_The_Lord_is_my_shepherd_",
    "50_pentagon2_",
    "51_Raisedstart_",
    "52b_sponge",
    "53_sunshine_",
    "54_SwoopyRadiance_",
    "55_traingles22",
    "56_yingyang_",
    "58_squares_",
    "59_sisinfturn_",
    "60_pentagontriangles_",
    "61b_SixPennyHandley__",
    "63_hexagonalley_",
    "64b_I_Love_you_Jess",
    "65_heartswirl_",
    "66_KeysleyDown_",
    "67_Muncombe_Hill_",
    "68_Polarvalentine_(",
    "69b_StarryNight_",
    "70_spiralsquareeraser_",
    "71_Snowflake_",
    "72b_loveballoon",
    "73_OaereWiltshire_",
    "74b_twofaces_",
    "75_WinterbourneStokedown_",
    "76_tri4_",
    "77_Milkhill2_",
    "78_LiddingtonCastle_",
    "79_LongwoodWarrenHants_",
    "80_strangthang_",
    "十二生肖_兔",
    "十二生肖_牛",
    "十二生肖_狗",
    "十二生肖_猪",
    "十二生肖_猴",
    "十二生肖_羊",
    "十二生肖_虎",
    "十二生肖_蛇",
    "十二生肖_马",
    "十二生肖_鸡",
    "十二生肖_鼠",
    "十二生肖_龙",
    "星座_双子座",
    "星座_双鱼座",
    "星座_处女座",
    "星座_天秤座",
    "星座_天蝎座",
    "星座_射手座",
    "星座_巨蟹座",
    "星座_摩羯座",
    "星座_水瓶座",
    "星座_狮子座",
    "星座_白羊座",
    "星座_金牛座",
    "热门图片-01",
    "热门图片-02",
    "热门图片-03",
    "热门图片-04",
    "热门图片-05",
    "热门图片-06",
    "热门图片-07",
    "热门图片-08",
    "热门图片-09",
    "热门图片-10",
    "热门图片-11",
    "热门图片-12",
    "龙年大吉"
]

# 用rename_list中的名字来重命名./www/media/re/中的mp3文件
def rename_files(path):
    for root, dirs, files in os.walk(path):
        for file in files:
            if file.endswith('.mp3'):
                new_file = rename_list.pop(0) + '.mp3'
                os.rename(os.path.join(root, file), os.path.join(root, new_file))
                print('Renamed:', file, '->', new_file)


rename_files('./www/media/re')
